language: python
python: 
  - 3.4
  - 3.5
  - 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install -r requirements_test.txt
script:
  - pytest --cov=./
after_script:
- codecov
